### ISSUE TITLE
question not issue

### ISSUE THREAD

**Issue by Noel388** [antononcube/SystemModeling#1]
Hi, sorry for approaching you through an issue, but i can't find any other way to contact you. So i have a question on the post you create about "Directional quantile envelops" (https://mathematicaforprediction.wordpress.com/2014/11/03/directional-quantile-envelopes/). I am wondering what are some reasons to apply this methods? This is because I am trying to apply this to a heart disease data (https://www.kaggle.com/ronitf/heart-disease-uci); do you think it is possible?

Thank you so much and sorry for any inconvenient that might have caused you.

**Comment by antononcube** [comment]
- Thank you for your interest in the article ["Directional quantile envelops"](https://mathematicaforprediction.wordpress.com/2014/11/03/directional-quantile-envelopes/)!

- This is the wrong repository for this question. You should have posted it at [MathematicaForPrediction at GitHub](https://github.com/antononcube/MathematicaForPrediction).

- The reason to use the methods in that article are discussed in [this Mathematica StackExchange post](https://mathematica.stackexchange.com/a/114032/34008). (See also the comments.)

**Comment by Noel388** [comment]
Thank you! Really nice articles and comments!
