### ISSUE TITLE
partition Germany into a network of sites

### ISSUE THREAD

**Issue by gitporst** [antononcube/SystemModeling#5]

**Comment by gitporst** [comment]
The file https://wirvsvirus.slack.com/files/U010FSTK0H3/F0104JV8RJN/2waytraffic.xlsx is based on cities, census and economy will be based on NUTS regions (e.g. 3 - "Kreis-Ebene"). The model uses hexagons, but is rather flexible. So I propose to go with NUTS3 and optionally remap that later onto hexagons...

**Comment by antononcube** [comment]
I did partition Germany into a network of sites for WirWsVirus hackathon, but this is not an issue relevant to this repository.
