### ISSUE TITLE
Mind map tool

### ISSUE THREAD

**Issue by alcazar90** [antononcube/SystemModeling#8]
Hi Anton!

First of all, thanks for the presentation and the material.
What tools did you use to build the mind map tree which you used to guide all the presentation?

Nice visualization to guide a presentation and keep all pieces and its relationships together visually.

Regards.
Cristóbal

**Comment by antononcube** [comment]
Hi Cristóbal,
Thank you!

The mind-map tool is called MindNode, see https://mindnode.com .
